# Generated by Django 5.2.4 on 2025-07-10 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actor_name_alter_genre_name_alter_movie_actors_and_more'),
        ('users', '0002_otpcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text="User's phone number for OTP", max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.IntegerField(help_text='4-digit OTP code'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.CharField(help_text='Phone number for OTP', max_length=11),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, help_text="User's favorite movies", related_name='favorited_by', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='watched_movies',
            field=models.ManyToManyField(blank=True, help_text='Movies the user has watched', related_name='watched_by', to='movies.movie'),
        ),
    ]
