# Generated by Django 5.2.4 on 2025-07-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(help_text='Name of the actor', max_length=100),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Name of the genre', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(help_text='Actors in the movie', related_name='movies', to='movies.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(help_text='Genres associated with the movie', related_name='movies', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, help_text='Poster image of the movie', null=True, upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot_summary',
            field=models.TextField(help_text="Summary of the movie's plot"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')], default=0.0, help_text='Rating out of 5'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Title of the movie', max_length=200),
        ),
    ]
